 set tv ntsc
 set romsize 4k

 rem **************************************************************************
 rem Title: atari 2600 game intro
 rem Developer: fanmad
 rem Version: 1
 rem Email: dawidfaron445@gmail.com
 rem
 rem Description:
 rem just a simple intro for a2600 homebrew games
 rem
 rem **************************************************************************
 rem Created with VCS Game Maker.
 rem Create your own Atari VCS games: https://haroldo-ok.itch.io/vcs-game-maker
 rem **************************************************************************

 rem **************************************************************************
 rem Options
 rem **************************************************************************
 set kernel_options playercolors player1colors pfcolors
 const noscore = 1






 

 rem **************************************************************************
 rem Setup: 
 rem - set initial values
 rem **************************************************************************
 COLUBK = $0F
 score = 00000 :  scorecolor = $08

 const true = 1
 const false = 0

 dim player0frame = x  ; real bB kernel var: which graphic frame player0 shows
 dim player1frame = z  ; real bB kernel var: which graphic frame player1 shows
 dim newbackground = y  ; real bB kernel var: which background is currently selected
 dim player0size = t  ; restores NUSIZ0 every frame (score routine clobbers it)
 dim player1size = s  ; restores NUSIZ1 every frame (score routine clobbers it)
 dim player0realcolor = r  ; restores COLUP0 every frame (score routine clobbers it)
 dim player1realcolor = q  ; restores COLUP1 every frame (score routine clobbers it)
 dim playfieldrealcolor = m  ; restores COLUPF every frame (score routine clobbers it)
 dim backgroundrealcolor = l  ; restores COLUBK every frame (score routine clobbers it)
 dim player0animation = p  ; which animation is currently playing on player0
 dim player1animation = o  ; which animation is currently playing on player1
 dim framecounter = n  ; free-running frame counter, default fallback for several features

 newbackground = 1

 player0x = 75 : player0y = 75
 player1x = 75 : player1y = 25
 ballx = 0 : bally = 0

 player1realcolor = $80
 player0realcolor = $40
 playfieldrealcolor = $0E
 backgroundrealcolor = $C4
 player1size = $30
 player0size = $30
 COLUBK = backgroundrealcolor
 player0animation = 1




  rem **************************************************************************
  rem Event: system_start.
  rem **************************************************************************
system_start_begin
  newbackground = 1
  backgroundrealcolor = 0
  _musicCh0Index = 0
  _musicCh0Timer = 1
  _musicFlags{3} = 1
  _musicCh1Index = 0
  _musicCh1Timer = 1
  _musicFlags{4} = 1
  _musicFlags{0} = 1
  _musicFlags{1} = 0
  _musicFlags{2} = 0
  _musicFlags{5} = 0
  for repeatcounter = 1 to 20
  temp1 = 255
  for _waitFramesCounter = 1 to temp1 : gosub commongamelogic : drawscreen : next
  temp1 = 255
  for _waitFramesCounter = 1 to temp1 : gosub commongamelogic : drawscreen : next
  temp1 = 255
  for _waitFramesCounter = 1 to temp1 : gosub commongamelogic : drawscreen : next
  temp1 = 255
  for _waitFramesCounter = 1 to temp1 : gosub commongamelogic : drawscreen : next
  temp1 = 255
  for _waitFramesCounter = 1 to temp1 : gosub commongamelogic : drawscreen : next
  next
  newbackground = 2
  temp1 = 255
  for _waitFramesCounter = 1 to temp1 : gosub commongamelogic : drawscreen : next
  temp1 = 255
  for _waitFramesCounter = 1 to temp1 : gosub commongamelogic : drawscreen : next
  newbackground = 3
system_start_end

fullgameloop

  rem **************************************************************************
  rem Event: title_start.
  rem **************************************************************************
title_start_begin

title_start_end

  rem **************************************************************************
  rem Event: title_update.
  rem **************************************************************************
title_update_begin

title_update_end

  rem **************************************************************************
  rem Event: gameplay_start.
  rem **************************************************************************
gameplay_start_begin

gameplay_start_end

 rem **************************************************************************
 rem Main loop: 
 rem **************************************************************************
main

 gosub commongamelogic
 drawscreen

 rem **************************************************************************
 rem Code generated by VCS Game Maker.
 rem **************************************************************************

  dim _musicCh0Index = a  ; this channel's own position within its current pattern
  dim _musicCh0Timer = b  ; this channel's own frames-left-on-current-note countdown
  dim _musicCh0LastAudc = c  ; this channel's own last-played AUDC value
  dim _musicCh1Index = d  ; this channel's own position within its current pattern
  dim _musicCh1Timer = e  ; this channel's own frames-left-on-current-note countdown
  dim _musicCh1LastAudc = f  ; this channel's own last-played AUDC value
  dim _musicFlags = g  ; shared playing/loop/stopped/per-channel-active bit-flags byte
  dim _repeatBound = h  ; "Repeat X times" own bound, when X is a complex expression
  dim repeatcounter = i  ; "Repeat X times" own for-loop counter
  dim _waitFramesCounter = j  ; "Wait N frames" own for-loop counter
  dim channnel0duration = k  ; frames left before AUDV0 auto-silences
  dim channnel1duration = u  ; frames left before AUDV1 auto-silences
  dim rand16 = v  ; literal name the standard kernel checks for to widen the RNG period


  

 rem **************************************************************************
 rem End of generated code.
 rem **************************************************************************



 goto main
 
  rem **************************************************************************
  rem Event: gameover_start.
  rem **************************************************************************
gameover_start_begin

gameover_start_end

  rem **************************************************************************
  rem Event: gameover_update.
  rem **************************************************************************
gameover_update_begin

gameover_update_end

 goto fullgameloop

 rem **************************************************************************
 rem Common game logic subroutine.
 rem **************************************************************************

commongamelogic

 framecounter = framecounter + 1

 rem **************************************************************************
 rem "Run once" block bookkeeping - see event_run_once/generateRunOnceEdgeReset.
 rem **************************************************************************





 rem **************************************************************************
 rem Sound handling.
 rem **************************************************************************

 asm
       lda channnel0duration
       beq _channeldurationasm0_skip
       cmp #1
       bne _channeldurationasm0_mute_skip
       lda #0
       sta AUDV0
_channeldurationasm0_mute_skip
       dec channnel0duration
_channeldurationasm0_skip
       lda channnel1duration
       beq _channeldurationasm1_skip
       cmp #1
       bne _channeldurationasm1_mute_skip
       lda #0
       sta AUDV1
_channeldurationasm1_mute_skip
       dec channnel1duration
_channeldurationasm1_skip
end




 rem **************************************************************************
 rem Music engine by AbstractPolygon - https://abstractpolygon.com/
 rem **************************************************************************

 if channnel0duration <> 1 then goto _musicresume0_skip
 if !_musicFlags{3} then goto _musicresume0_skip
 if _musicCh0Index < 3 then goto _musicresume0_skip
 temp1 = _musicCh0Index - 3
 temp1 = _musicCh0Data0[temp1]
 AUDV0 = temp1
 AUDC0 = _musicCh0LastAudc
 temp1 = _musicCh0Index - 2
 temp1 = _musicCh0Data0[temp1]
 AUDF0 = temp1
_musicresume0_skip
 asm
       lda _musicFlags
       and #$20
       beq _music0_hp_notpaused
       jmp ._music0_skip
_music0_hp_notpaused
       lda _musicFlags
       and #$8
       bne _music0_hp_active
       jmp ._music0_skip
_music0_hp_active
       dec _musicCh0Timer
end
 if _musicCh0Timer <> 0 then goto _music0_skip
 temp1 = _musicCh0Data0[_musicCh0Index]
 gosub _music0_skipinstr
 if temp1 <> 255 then goto _music0_read
 if _musicFlags{1} then goto _music0_loopreset
 if channnel0duration <> 0 then goto _musicsup0_audvsingleend_skip
 AUDV0 = 0
_musicsup0_audvsingleend_skip
 _musicFlags{3} = 0
 if _musicFlags{4} then goto _music0_skip
 _musicFlags{0} = 0
 _musicFlags{2} = 1
 goto _music0_skip
_music0_loopreset
 _musicCh0Index = 0
 temp1 = _musicCh0Data0[_musicCh0Index]
 gosub _music0_skipinstr
_music0_read
 _musicCh0Index = _musicCh0Index + 1
 if channnel0duration <> 0 then goto _musicsup0_audvfetch_skip
 AUDV0 = temp1
_musicsup0_audvfetch_skip
 temp1 = _musicCh0Data0[_musicCh0Index]
 _musicCh0Index = _musicCh0Index + 1
 if channnel0duration <> 0 then goto _musicsup0_audfplain_skip
 AUDF0 = temp1
_musicsup0_audfplain_skip
 temp1 = _musicCh0Data0[_musicCh0Index]
 _musicCh0Index = _musicCh0Index + 1
 _musicCh0Timer = temp1
_music0_skip

 if channnel1duration <> 1 then goto _musicresume1_skip
 if !_musicFlags{4} then goto _musicresume1_skip
 if _musicCh1Index < 3 then goto _musicresume1_skip
 temp1 = _musicCh1Index - 3
 temp1 = _musicCh1Data0[temp1]
 AUDV1 = temp1
 AUDC1 = _musicCh1LastAudc
 temp1 = _musicCh1Index - 2
 temp1 = _musicCh1Data0[temp1]
 AUDF1 = temp1
_musicresume1_skip
 asm
       lda _musicFlags
       and #$20
       beq _music1_hp_notpaused
       jmp ._music1_skip
_music1_hp_notpaused
       lda _musicFlags
       and #$10
       bne _music1_hp_active
       jmp ._music1_skip
_music1_hp_active
       dec _musicCh1Timer
end
 if _musicCh1Timer <> 0 then goto _music1_skip
 temp1 = _musicCh1Data0[_musicCh1Index]
 gosub _music1_skipinstr
 if temp1 <> 255 then goto _music1_read
 if _musicFlags{1} then goto _music1_loopreset
 if channnel1duration <> 0 then goto _musicsup1_audvsingleend_skip
 AUDV1 = 0
_musicsup1_audvsingleend_skip
 _musicFlags{4} = 0
 if _musicFlags{3} then goto _music1_skip
 _musicFlags{0} = 0
 _musicFlags{2} = 1
 goto _music1_skip
_music1_loopreset
 _musicCh1Index = 0
 temp1 = _musicCh1Data0[_musicCh1Index]
 gosub _music1_skipinstr
_music1_read
 _musicCh1Index = _musicCh1Index + 1
 if channnel1duration <> 0 then goto _musicsup1_audvfetch_skip
 AUDV1 = temp1
_musicsup1_audvfetch_skip
 temp1 = _musicCh1Data0[_musicCh1Index]
 _musicCh1Index = _musicCh1Index + 1
 if channnel1duration <> 0 then goto _musicsup1_audfplain_skip
 AUDF1 = temp1
_musicsup1_audfplain_skip
 temp1 = _musicCh1Data0[_musicCh1Index]
 _musicCh1Index = _musicCh1Index + 1
 _musicCh1Timer = temp1
_music1_skip

 goto _music_update_data_skip

_music0_skipinstr
 if temp1 <> 253 then goto _music0_skipinstr_done
 _musicCh0Index = _musicCh0Index + 1
 temp1 = _musicCh0Data0[_musicCh0Index]
 _musicCh0Index = _musicCh0Index + 1
 temp1 = _musicInstruments[temp1]
 _musicCh0LastAudc = temp1
 if channnel0duration <> 0 then goto _musicsup0_audc_skip
 AUDC0 = temp1
_musicsup0_audc_skip
 temp1 = _musicCh0Data0[_musicCh0Index]
 goto _music0_skipinstr
_music0_skipinstr_done
 return

_music1_skipinstr
 if temp1 <> 253 then goto _music1_skipinstr_done
 _musicCh1Index = _musicCh1Index + 1
 temp1 = _musicCh1Data0[_musicCh1Index]
 _musicCh1Index = _musicCh1Index + 1
 temp1 = _musicInstruments[temp1]
 _musicCh1LastAudc = temp1
 if channnel1duration <> 0 then goto _musicsup1_audc_skip
 AUDC1 = temp1
_musicsup1_audc_skip
 temp1 = _musicCh1Data0[_musicCh1Index]
 goto _music1_skipinstr
_music1_skipinstr_done
 return

 rem Channel 0 for tada note data (AUDV, AUDF, duration per note - instrument changes are interleaved as their own 2-byte markers, see the instrument table below)
 data _musicCh0Data0
  253, 0, 2, 9, 48, 0, 0, 147, 255
end

 rem Channel 1 for tada note data (AUDV, AUDF, duration per note - instrument changes are interleaved as their own 2-byte markers, see the instrument table below)
 data _musicCh1Data0
  253, 0, 2, 13, 24, 2, 11, 24, 0, 0, 147, 255
end

 rem Shared instrument table (AUDC|arpeggioSpeed<<4 per instrument) - indexed by an INSTRUMENT_CHANGE_SENTINEL marker in the note data above
 data _musicInstruments
  4
end

_music_update_data_skip









 rem **************************************************************************
 rem - Draws the screen and handles user input. Moves the sprites and
 rem - the ball's position and handles collisions
 rem **************************************************************************
 COLUP1 = player1realcolor
 COLUP0 = player0realcolor
 COLUPF = playfieldrealcolor
 COLUBK = backgroundrealcolor
 pfscorecolor = scorecolor
 NUSIZ0 = player0size
 NUSIZ1 = player1size
 if player0size{3} then REFP0 = 8 else REFP0 = 0
 if player1size{3} then REFP1 = 8 else REFP1 = 0

 rem **************************************************************************
 rem Backgrounds generated by VCS Game Maker.
 rem **************************************************************************

 if newbackground = 0 then goto backgroundchangeend
 if newbackground <> 1 then goto background1end
 playfield:
  ......X...XXX...X...XX...X......
  .....X.X...X...X.X..X.X..X......
  ................................
  ......XX.....X...XXX.XXX........
  .......XX...X....X.X.X.X........
  ......XXXX..XXX..XXX.XXX........
  .....XXXXXXXXXXXXXXXXXXXXXXX....
  ....XXXXXXXXXXXXXXXXXXXXXXXXX...
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXX..
  ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
  ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
end
 pfcolors:
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $04
  $06
  $08
  $24
  $22
  $22
end
 playfieldrealcolor = $0E
background1end

 if newbackground <> 2 then goto background2end
 playfield:
  ......X...XXX...X...XX...X......
  .....X.X...X...X.X..X.X..X......
  ................................
  ......XX.....X...XXX.XXX........
  .......XX...X....X.X.X.X........
  ......XXXX..XXX..XXX.XXX........
  .....XXXXXXXXXXXXXXXXXXXXXXX....
  ....XXXXXXXXXXXXXXXXXXXXXXXXX...
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXX..
  ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
  ................................
end
 pfcolors:
  $06
  $06
  $0E
  $06
  $06
  $06
  $02
  $04
  $06
  $22
  $20
  $20
end
 playfieldrealcolor = $06
background2end

 if newbackground <> 3 then goto background3end
 playfield:
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
end
 pfcolors:
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
end
 playfieldrealcolor = $0E
background3end
backgroundchangeend
 newbackground = 0

 rem **************************************************************************
 rem Animations generated by VCS Game Maker.
 rem **************************************************************************

   rem Animations for player0:

  if player0frame <> 255 then goto player0animationsStart
  player0:
  %00000000
end
  goto player0animationsEnd

player0animationsStart

player0animation0Start

  rem Animation 0 Example1 for player0:

  if player0size{6} then goto player0animation0pauseSkip
  player0frame = player0frame + 1
  if player0frame >= 10 then player0frame = 0
player0animation0pauseSkip

  if player0frame > 10 then goto player0animation0frame0End
player0animation0frame0Graphic
  player0:
  %00000000
  %00000000
  %00000000
  %00000000
  %00000000
  %00000000
  %00000000
  %00000000
end
  player0color:
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
end
  goto player0animation0animationEnd
player0animation0frame0End

player0animation0animationEnd
  goto player0animationsEnd

player0animationsEnd


  rem Animations for player1:

  if player1frame <> 255 then goto player1animationsStart
  player1:
  %00000000
end
  goto player1animationsEnd

player1animationsStart

player1animation0Start

  rem Animation 0 Example1 for player1:

  if player1size{6} then goto player1animation0pauseSkip
  player1frame = player1frame + 1
  if player1frame >= 10 then player1frame = 0
player1animation0pauseSkip

  if player1frame > 10 then goto player1animation0frame0End
player1animation0frame0Graphic
  player1:
  %00000000
  %00000000
  %00000000
  %00000000
  %00000000
  %00000000
  %00000000
  %00000000
end
  player1color:
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
  $0E
end
  goto player1animation0animationEnd
player1animation0frame0End

player1animation0animationEnd
  goto player1animationsEnd

player1animationsEnd





 return

 rem **************************************************************************
 rem Subroutines generated by VCS Game Maker.
 rem
 rem Same reason these must stay past this point as the data tables below:
 rem never reached by falling through normal execution, only entered via
 rem "gosub" and left via "return".
 rem **************************************************************************





 rem **************************************************************************
 rem Data tables generated by VCS Game Maker.
 rem
 rem These must stay past this point: a "data" block is a read-only ROM table,
 rem not executable code, and this is the only spot in the file that is never
 rem reached by falling through normal execution (everything above either
 rem loops back with "goto" or returns from a "gosub").
 rem **************************************************************************

 data _dt_1_Example_table
  0, 1, 2, 3
end













 asm
minikernel
       sta WSYNC
       lda backgroundrealcolor
       sta COLUBK
       rts
end
